### ISSUE TITLE
ignore_errors on restart Dock and use notify

### ISSUE THREAD

**Issue by daften** [fubarhouse/ansible-role-macdock#6]
On rare cases, mainly testing purposes, the dock process isn't launched yet. This could also be the case for remote management (when mas-cli finally runs over ssh that is). I'd propose to add ignore_errors on restart Dock.
And also to put that task in handlers and add a notify to the removed, added and changed tasks to trigger a dock restart

If you let me know what you think, I can whip up a PR quickly.

**Comment by fubarhouse** [comment]
Would it be a better idea to test if the process has been started, and provide some logic to skip restarting the dock if it hasn't been started?

If that wouldn't be better than what you've proposed - could you explain why; and **I'll happily accept a PR**.

The reason I ask is that I've used ignore_errors quite a bit in the past and I've had a range of mixed results which generally lead to more development work or rewrites - and the whole idea of ignoring something because something unexpected happened should be handled differently (more elegantly).

My approach would be:
* Identify how to store the status of the process in a variable
* Provide some logic to support this in the relevant tasks

**Comment by mraerino** [comment]
I added #7 to use a handler instead of a complicated way to check if something changed. I hope this solves this issue somewhat.

**Comment by fubarhouse** [comment]
@mraerino I'm happy with those changes - I've just merged them.

They should fix the problems raised in this issue, and they also avoid the use of ignore_errors.

@daften, the task which causes the error has been removed altogether in favour of notify.

Would these changes prevent the scenario's you've raised from failing, or would more work be required?

**Comment by daften** [comment]
Sorry for the late reply and thanks for keeping this open. This is part of it. If the Dock process isn't launched yet, the run would still fail. In case there are handlers that need to run after this, they wouldn't be run. I'd still add a changed_when: false and ignore_errors: yes to the handler itself.

Changed_when false because restarting a process doesn't actually really change anything, it's the dockutil commands that make the changes.

And ignore_errors because killing a process can only really fail because of two things: the process doesn't exist or you don't have permissions to do it. The first case can be ignored and the second won't happen for the Dock process I think. If you think that would cause errors, I can whip up a patch with the behaviour of checking if dock is launched.

**Comment by fubarhouse** [comment]
I'd be happy to accept a PR with the changes to the handler.

With that said, it would be my preference to use `failed_when: false` instead of `ignore_errors: yes`

Preventing a task from being marked as a failure doesn't include the same burdens as ignoring errors directly. However, If you feel this isn't suitable I'll accept a PR with the `ignore_errors` flag.

After this issue is closed, I'll draft up a release to get this on the galaxy.

**Comment by daften** [comment]
I'm fairly new to ansible, so I forgot about failed_when. I'll read up on the differences and make a PR. Thanks! :)

**Comment by fubarhouse** [comment]
Cool! I'll fix up a new release in the next 24 hours -as I'm literally about to go to sleep.

**Comment by daften** [comment]
No worries, thanks for the help and patience. Have a good night!

**Comment by fubarhouse** [comment]
Version v2.1 is now released to the Galaxy, with you both being credited for the changes in the release notes. :)
